const ProductList = [
    {
      'price': 230,
      'instock': 9,
      'sold': 8745,
      'image': 'images/spoon.jpg',
      'title':'The Hole-y Spoon',
      'description': 'Designed for those who value innovation and efficiency. Its unique perforated design ensures optimal liquid flow, making it the perfect choice for minimalist meals and avant-garde culinary experiences.',
    },
    {
      'price': 5230,
      'instock': 59,
      'sold': 245,
      'image': 'images/phone.jpg',
      'title':'The Compact Super Communicator X2000B',
      'description': 'A masterpiece of engineering and design. This larger-than-life device combines vintage aesthetics with modern functionality, featuring intricate valves, gears, and brass finishes. Designed for those who appreciate bold statements, it comes with ergonomic handles for easy transport. Redefine communication with this unparalleled blend of art and technology',
    },
    {
      'price': 2230,
      'instock': 22,
      'sold': 145,
      'image': 'images/piano.jpg',
      'title':'The Silent Maestro',
      'description': 'For those who cherish silence but still crave the artistry of Mozart, The Silent Maestro Piano is here to redefine your musical experience. This innovative instrument removes the distraction of sound, allowing you to focus solely on the elegance of your performance. With its sleek, keyless design, it’s perfect for the minimalist musician who values imagination over noise. Play the symphony in your mind—without disturbing a soul.',
    },
    {
      'price': 330,
      'instock': 559,
      'sold': 1245,
      'image': 'images/umbrella.jpg',
      'title':'The Precision Rain Shield',
      'description': 'Say goodbye to getting completely soaked with The Precision Rain Shield. This innovative umbrella features strategically placed perforations, ensuring you stay dry where it matters most. Perfect for those who appreciate a touch of unpredictability in their rainy-day gear, it’s the ultimate blend of functionality and avant-garde design. Stay dry—just not entirely.',
    },
    {
      'price': 330,
      'instock': 19,
      'sold': 745,
      'image': 'images/toothbrush.jpg',
      'title':'The BristleFree X2000',
      'description': 'Step into the future of oral hygiene with The BristleFree X2000. This cutting-edge toothbrush eliminates the need for traditional bristles, offering a sleek, smooth surface for a truly minimalist brushing experience. Designed for the modern innovator, it’s perfect for those who want to simplify their routine without sacrificing style. Brushing has never been this advanced—or this smooth.',
    },
    {
      'price': 100353,
      'instock': 3,
      'sold': 845,
      'image': 'images/shrek.jpg',
      'title':'The ShrekTech Armor XSWamp9000',
      'description': 'Unleash your inner ogre with The ShrekTech Armor X9000, the ultimate fusion of fantasy and futuristic technology. This state-of-the-art robotic armor combines Shrek’s iconic style with advanced engineering, offering unparalleled protection and style. Whether you’re defending your swamp or just making a bold fashion statement, this armor is your go-to choice. Ogres have never been this high-tech.',
    },
    {
      'price': 83.20,
      'instock': 53,
      'sold': 8425,
      'image': 'images/metal back.jpg',
      'title':'The SteelHug CarryMaster 5000',
      'description': 'Introducing The SteelHug CarryMaster 5000, the ultimate in minimalist, hands-free storage solutions. Crafted from premium, ultra-durable steel, this strapless backpack redefines portability by encouraging a more intimate carrying experience—right in your arms. Perfect for those who value strength and simplicity, it’s the ideal choice for anyone looking to build muscle while carrying their essentials. Because why settle for convenience when you can have a challenge?',
    },
    {
      'price': 483,
      'instock': 23,
      'sold': 45,
      'image': 'images/sax.jpg',
      'title':'The SilentSax SoundBlocker HyperSnake',
      'description': 'Experience the future of musical innovation with The SilentSax SoundBlocker HyperSnake. This revolutionary saxophone eliminates the need for holes, offering a sleek, seamless design that redefines what it means to play an instrument. Perfect for those who value silence and style, it’s the ultimate choice for musicians who want to look the part without the noise. Because sometimes, the best music is the one you don’t hear.',
    },
    {
      'price': 483,
      'instock': 1223,
      'sold': 1245,
      'image': 'images/tv.jpg',
      'title':'The Screenless VisionMaster Quantum-X',
      'description': 'Step into the future of entertainment with The Screenless VisionMaster Quantum-X, the world’s first television that doesn’t need a screen. Using cutting-edge imagination technology, this TV allows you to visualize your favorite shows, movies, and games in your mind. Perfect for minimalists and forward-thinkers, it’s the ultimate way to enjoy entertainment without the clutter. Why watch on a screen when you can dream in HD?',
    },
    {
      'price': 33,
      'instock': 1123,
      'sold': 8245,
      'image': 'images/oculos.jpg',
      'title':'The WoodenVision TimberLens 5000',
      'description': 'Experience the world through nature’s lens with The WoodenVision TimberLens 5000. These revolutionary glasses feature solid wood frames and lenses, offering a truly unique perspective on life. Perfect for those who value sustainability and bold fashion statements, they’re the ultimate choice for anyone who dont wants to see the world—literally—through a different lens. Because why settle for clarity when you can have craftsmanship?',
    },
    {
      'price': 633,
      'instock': 125,
      'sold': 1875,
      'image': 'images/mirror.jpg',
      'title':'The DarkReflect VoidMaster Ultra',
      'description': 'Introducing The DarkReflect VoidMaster Ultra, the world’s first non-reflective mirror. With its revolutionary pitch-black surface, this mirror allows you to gaze into the void and embrace the mystery of nothingness. Perfect for those who value introspection and avant-garde design, it’s the ultimate statement piece for anyone who dares to question reality. Why reflect the world when you can reflect on existence itself?',
    },
    {
      'price': 21633,
      'instock': 125,
      'sold': 1875,
      'image': 'images/car.jpg',
      'title':'The HorseDrive EcoGlide Turbo-X',
      'description': 'Revolutionize your commute with The HorseDrive EcoGlide Turbo-X, the ultimate fusion of classic horsepower and modern design. This innovative vehicle combines the elegance of horse-drawn carriages with the convenience of a car, offering a truly unique and eco-friendly transportation experience. Perfect for those who value tradition and sustainability, it’s the ultimate choice for anyone who wants to travel in style—without the gas. Because why drive when you can ride in timeless elegance?',
    },
    {
      'price': 398,
      'instock': 25,
      'sold': 22875,
      'image': 'images/basket.jpg',
      'title':'The SlamDunk Blocker Pro 9000',
      'description': 'Introducing The SlamDunk Blocker Pro 9000, the world’s first basketball hoop designed to challenge the very concept of scoring. With its patented screw-on lid, this hoop ensures that no ball shall pass, offering a truly unique and frustration-filled gaming experience. Perfect for those who value innovation and a good challenge, it’s the ultimate choice for anyone who dares to redefine the rules of the game. Why score points when you can master the art of futility?',
    },
    {
      'price': 98,
      'instock': 825,
      'sold': 875,
      'image': 'images/mag.jpg',
      'title':'The ShrinkScope Minimizer XTreme',
      'description': 'Discover the world from a whole new perspective with The ShrinkScope Minimizer XTreme, the first lens that makes everything look smaller. Using revolutionary reverse-magnification technology, this lens challenges your perception of reality, offering a truly unique and mind-bending experience. Perfect for those who value innovation and a touch of absurdity, it’s the ultimate tool for anyone who dares to see the world differently. Why magnify when you can minimize?',
    },
    {
      'price': 988,
      'instock': 85,
      'sold': 7725,
      'image': 'images/fone.jpg',
      'title':'TTe SilentBeats SoundNull 3000',
      'description': 'Experience the future of audio with The SilentBeats SoundNull 3000, the world’s first headphones designed to deliver nothing but pure silence. Featuring a revolutionary no-sound technology, these headphones eliminate all audio output, offering a truly immersive and distraction-free listening experience. Perfect for those who value peace and quiet, it’s the ultimate choice for anyone who dares to embrace the sound of nothing. Why listen to music when you can listen to silence?',
    },
    {
      'price': 8,
      'instock': 185,
      'sold': 27725,
      'image': 'images/fork.jpg',
      'title':'The NoodleFork FlexiChain 2000',
      'description': 'Introducing The NoodleFork FlexiChain 2000, the ultimate utensil for those who love a challenge. Featuring a revolutionary flimsy chain handle, this fork redefines the art of dining by adding an element of unpredictability to every bite. Perfect for adventurous eaters and minimalist designers, it’s the ultimate choice for anyone who dares to embrace the chaos of mealtime. Why settle for stability when you can dine on the edge?',
    },
    {
      'price': 38,
      'instock': 1895,
      'sold': 654,
      'image': 'images/dvd.jpg',
      'title':'The DVD RewindMaster Turbo-X',
      'description': 'Step into the future of retro technology with The DVD RewindMaster Turbo-X, the world’s first DVD rewinder. Designed for those who miss the satisfying click of rewinding, this device brings the nostalgia of VHS to your DVD collection. Perfect for cinephiles and tech enthusiasts, it’s the ultimate choice for anyone who dares to rewind the un-rewindable. Why settle for fast-forward when you can rewind in style?',
    },
    {
      'price': 1238,
      'instock': 185,
      'sold': 1654,
      'image': 'images/fireplace.jpg',
      'title':'The FlameFree HearthMaster 5000',
      'description': 'Introducing The FlameFree HearthMaster 5000, the world’s first hole-less fireplace. This revolutionary design eliminates the need for flames, smoke, or heat, offering a truly unique and minimalist hearth experience. Perfect for those who value aesthetics over functionality, it’s the ultimate choice for anyone who dares to redefine the concept of warmth. Why have a fire when you can have the idea of one?',
    },
    {
      'price': 8,
      'instock': 1285,
      'sold': 654,
      'image': 'images/candle.jpg',
      'title':'The ShrCandle NoWick 3000',
      'description': 'Introducing The ShrCandle NoWick 3000, the world’s first Shrek-themed candle designed to never be lit. With its revolutionary wick-less design, this candle offers all the ambiance of a swamp without the hassle of fire. Perfect for Shrek enthusiasts and minimalist decorators, it’s the ultimate choice for anyone who dares to embrace the essence of Shrek—without the flame.',
    },
    {
      'price': 848,
      'instock': 5,
      'sold': 6581,
      'image': 'images/clock.jpg',
      'title':'The TimeLess ChronoNull 9000',
      'description': 'Introducing The TimeLess ChronoNull 9000, the world’s first clock that challenges the very concept of time. With its revolutionary design, this clock eliminates the need for hands or numbers, offering a truly minimalist and thought-provoking timekeeping experience. Perfect for those who value innovation and a touch of absurdity, it’s the ultimate choice for anyone who dares to question the nature of time itself. ',
    },
  ]

  export default ProductList